# One CLI to format the code tree - https://github.com/numtide/treefmt
[formatter.nix]
command = "alejandra"
includes = ["*.nix"]
excludes = ["./cells/cardano/packages/materialized/*"]

[formatter.prettier]
command = "prettier"
options = ["--plugin", "prettier-plugin-toml", "--write"]
includes = ["*.md", "*.yaml", "*.toml"]

[formatter.shell]
command = "shfmt"
options = [
  "-i",
  "2", # indent 2
  "-s", # simplify the code
  "-w", # write back to the file

]
includes = ["*.sh"]
